# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_2 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.method(bool_0, bool_0)
    assert var_0 == 4


def test_case_1():
    complex_0 = -4095.411625 + 499.3467j
    bool_0 = False
    var_0 = module_0.method(complex_0, bool_0)
    assert var_0 == 5
    int_0 = -87
    var_1 = module_0.method(int_0, int_0)
    assert var_1 == 4


def test_case_2():
    bool_0 = True
    var_0 = module_0.method(bool_0, bool_0)
    assert var_0 == 4
    none_type_0 = None
    var_1 = module_0.method(bool_0, none_type_0)
    assert var_1 == 5
    var_2 = module_0.method(none_type_0, var_0)
    assert var_2 == 5
