# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example_3 as module_0


def test_case_0():
    int_0 = -2490
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.sorting(none_type_0)


def test_case_2():
    bool_0 = True
    int_0 = -2787
    list_0 = [bool_0, bool_0, int_0]
    var_0 = module_0.sorting(list_0)
