# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import two_sum as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    module_0.twoSum(list_0, list_0)
