# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import builtins as module_0
import test_example_2 as module_1


def test_case_0():
    object_0 = module_0.object()
    bool_0 = True
    var_0 = module_1.method(object_0, bool_0)
    assert var_0 == 4


def test_case_1():
    none_type_0 = None
    bool_0 = False
    var_0 = module_1.method(none_type_0, bool_0)
    assert var_0 == 6
