# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Quicksort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x8eH0\x17\x89c\xfc\x1c\xc7F."
    module_0.quicksort(bytes_0)
