# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_2 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.method(bool_0, bool_0)
    assert var_0 == 4


def test_case_1():
    bool_0 = True
    int_0 = 1287
    bool_1 = False
    var_0 = module_0.method(int_0, bool_1)
    assert var_0 == 5
    var_1 = module_0.method(bool_0, bool_0)
    assert var_1 == 4
    var_2 = module_0.method(bool_0, bool_0)
    assert var_2 == 4


def test_case_2():
    none_type_0 = None
    bool_0 = True
    var_0 = module_0.method(none_type_0, bool_0)
    assert var_0 == 5
    bool_1 = True
    var_1 = module_0.method(var_0, bool_1)
    assert var_1 == 4
