# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example_3 as module_0


def test_case_0():
    bool_0 = True
    bool_1 = True
    bool_2 = False
    list_0 = [bool_0, bool_1, bool_2]
    var_0 = module_0.sorting(list_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 160
    module_0.sorting(int_0)
