# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    module_0.serial_to_unique_id(list_0)
