# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Quicksort as module_0


def test_case_0():
    tuple_0 = ()
    var_0 = module_0.quicksort(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "\t*? *D!psHq9}~ep"
    module_0.quicksort(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.quicksort(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 2075
    list_0 = [int_0, int_0, int_0, int_0]
    module_0.quicksort(list_0)
