# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    var_0 = module_0.serial_to_unique_id(bool_0)
    assert var_0 == "00000000"
    module_0.serial_to_unique_id(var_0)
