# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example_3 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = '",5M[t]@=f.k;a;'
    module_0.sorting(str_0)


def test_case_1():
    int_0 = 1719
    list_0 = [int_0, int_0]
    var_0 = module_0.sorting(list_0)
    var_1 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.sorting(bool_0)
