# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Quicksort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = ":e9r9F^kOsGfX\x0boN"
    module_0.quicksort(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.quicksort(none_type_0)
