# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test_example_3 as module_0


def test_case_0():
    bytes_0 = b"U\xf3"
    var_0 = module_0.sorting(bytes_0)
    assert var_0 == b"U\xf3"


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "M#"
    module_0.sorting(str_0)
