# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example as module_0


def test_case_0():
    int_0 = -4045
    var_0 = module_0.serial_to_unique_id(int_0)
    assert var_0 == "0000xfcd"
