# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import two_sum as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x9d\r[M\xde\xec\x98\xee\x9c\x80\xa8_"
    module_0.twoSum(bytes_0, bytes_0)
