# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_2 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.method(bool_0, bool_0)
    assert var_0 == 4


def test_case_1():
    int_0 = -3839
    bool_0 = False
    bool_1 = False
    var_0 = module_0.method(bool_1, bool_0)
    assert var_0 == 6
    var_1 = module_0.method(int_0, bool_0)
    assert var_1 == 5


def test_case_2():
    bool_0 = False
    bool_1 = True
    var_0 = module_0.method(bool_0, bool_1)
    assert var_0 == 5
