# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import icon as module_0
import builtins as module_1


def test_case_0():
    str_0 = module_0.icon_for_signal_level()
    assert str_0 == "mdi:signal-cellular-outline"


def test_case_1():
    bool_0 = True
    str_0 = module_0.icon_for_signal_level(bool_0)
    assert str_0 == "mdi:signal-cellular-1"


def test_case_2():
    bool_0 = False
    str_0 = module_0.icon_for_signal_level(bool_0)
    assert str_0 == "mdi:signal-cellular-outline"


def test_case_3():
    str_0 = module_0.icon_for_signal_level()
    assert str_0 == "mdi:signal-cellular-outline"
    int_0 = 92
    str_1 = module_0.icon_for_signal_level(int_0)
    assert str_1 == "mdi:signal-cellular-3"
    str_2 = module_0.icon_for_signal_level()
    assert str_2 == "mdi:signal-cellular-outline"
    str_3 = module_0.icon_for_signal_level()
    assert str_3 == "mdi:signal-cellular-outline"
    str_4 = module_0.icon_for_signal_level()
    assert str_4 == "mdi:signal-cellular-outline"
    str_5 = module_0.icon_for_signal_level()
    assert str_5 == "mdi:signal-cellular-outline"
    str_6 = module_0.icon_for_signal_level()
    assert str_6 == "mdi:signal-cellular-outline"
    str_7 = module_0.icon_for_signal_level()
    assert str_7 == "mdi:signal-cellular-outline"


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = module_0.icon_for_signal_level()
    assert str_0 == "mdi:signal-cellular-outline"
    int_0 = 70
    str_1 = module_0.icon_for_signal_level(int_0)
    assert str_1 == "mdi:signal-cellular-2"
    str_2 = "O"
    dict_0 = {str_2: str_0, str_2: str_0, str_1: str_0}
    module_1.object(**dict_0)
