# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import _hashlib as module_0
import utils as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.HASHXOF()


def test_case_1():
    str_0 = "!"
    var_0 = module_1.hash_from_url(str_0)
    assert var_0 == "bb7208bc9b5d7c04f1236a82a0093a5e33f40423d5ba8d4266f7092c3ba43b62"
