# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import util as module_0


def test_case_0():
    int_0 = -1334
    str_0 = module_0.serial_to_unique_id(int_0)
    assert str_0 == "0000x536"
