# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
# Line Coverage: 100% Branch Coverage: 100% Mutation Score: 0%
import pytest
import helpers as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    complex_0 = 1927.124397 - 2236.79233j
    module_0.service_signal(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    str_0 = ""
    module_0.log_update_error(bool_0, bool_0, str_0, bool_0, bool_0, bool_0)
