# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import sub_example.test_example_3 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    int_0 = -1081
    list_0 = [bool_0, int_0, int_0]
    var_0 = module_0.sorting(list_0)
    module_0.sorting(bool_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.sorting(list_0)
    bool_0 = True
    list_1 = [bool_0, bool_0, bool_0, bool_0]
    var_1 = module_0.sorting(list_1)
    list_2 = []
    var_2 = module_0.sorting(list_2)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 1
    int_1 = 955
    list_0 = [int_0, int_1, int_0]
    var_0 = module_0.sorting(list_0)
    list_1 = [int_0]
    var_1 = module_0.sorting(list_1)
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -30
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0]
    var_0 = module_0.sorting(list_0)
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    list_0 = []
    var_0 = module_0.sorting(list_0)
    var_1 = module_0.sorting(list_0)
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = -3395
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    set_0 = set()
    var_0 = module_0.sorting(set_0)
    str_0 = "z>/."
    module_0.sorting(str_0)


def test_case_8():
    bool_0 = True
    int_0 = -2178
    list_0 = [bool_0, bool_0, int_0]
    var_0 = module_0.sorting(list_0)
    list_1 = []
    tuple_0 = (list_1,)
    var_1 = module_0.sorting(tuple_0)
    bool_1 = True
    int_1 = -740
    list_2 = [bool_1, int_1]
    var_2 = module_0.sorting(list_2)


def test_case_9():
    list_0 = []
    var_0 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_11():
    complex_0 = -232.8 - 471.62j
    module_0.sorting(complex_0)


def test_case_12():
    bool_0 = False
    int_0 = 926
    int_1 = -1938
    list_0 = [bool_0, int_0, bool_0, int_1]
    var_0 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    int_0 = 0
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)
    none_type_0 = None
    var_1 = module_0.sorting(var_0)
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    int_0 = 2498
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_15():
    str_0 = 'E.w"~Nd |'
    bool_0 = True
    list_0 = [bool_0, bool_0]
    var_0 = module_0.sorting(list_0)
    bool_1 = False
    bool_2 = False
    bool_3 = False
    list_1 = [bool_1, bool_2, bool_3]
    var_1 = module_0.sorting(list_1)
    module_0.sorting(str_0)


@pytest.mark.xfail(strict=True)
def test_case_16():
    int_0 = 28
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)
    var_1 = module_0.sorting(var_0)
    int_1 = -2599
    list_1 = [int_1]
    var_2 = module_0.sorting(list_1)
    var_3 = module_0.sorting(var_2)
    var_4 = module_0.sorting(var_0)
    none_type_0 = None
    module_0.sorting(none_type_0)


def test_case_17():
    list_0 = []
    var_0 = module_0.sorting(list_0)
    var_1 = module_0.sorting(list_0)
    bool_0 = False
    var_2 = module_0.sorting(var_0)
    bool_1 = False
    list_1 = [bool_0, bool_1]
    var_3 = module_0.sorting(list_1)
    var_4 = module_0.sorting(list_0)
    var_5 = module_0.sorting(var_1)


@pytest.mark.xfail(strict=True)
def test_case_18():
    bool_0 = True
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_19():
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_20():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    var_0 = module_0.sorting(list_0)
    float_0 = 1703.348
    dict_0 = {float_0: float_0, float_0: float_0, float_0: float_0, float_0: float_0}
    var_1 = module_0.sorting(dict_0)
    bool_1 = True
    module_0.sorting(bool_1)


@pytest.mark.xfail(strict=True)
def test_case_21():
    float_0 = -1006.604
    module_0.sorting(float_0)


@pytest.mark.xfail(strict=True)
def test_case_22():
    str_0 = "$PX `\"Veds'ioG.A0"
    module_0.sorting(str_0)


@pytest.mark.xfail(strict=True)
def test_case_23():
    int_0 = -2524
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)
    int_1 = 4709
    list_1 = [int_0, int_1, int_1, int_1]
    var_1 = module_0.sorting(list_1)
    module_0.sorting(int_1)


@pytest.mark.xfail(strict=True)
def test_case_24():
    int_0 = 1453
    int_1 = 608
    list_0 = [int_0, int_0, int_1, int_1]
    var_0 = module_0.sorting(list_0)
    list_1 = [int_0]
    var_1 = module_0.sorting(list_1)
    var_2 = module_0.sorting(list_1)
    list_2 = [int_0, int_0]
    var_3 = module_0.sorting(list_2)
    bool_0 = False
    list_3 = [bool_0]
    var_4 = module_0.sorting(list_3)
    var_5 = module_0.sorting(list_2)
    var_6 = module_0.sorting(list_2)
    var_7 = module_0.sorting(var_4)
    module_0.sorting(bool_0)


def test_case_25():
    bool_0 = True
    bool_1 = True
    int_0 = 2412
    list_0 = [bool_0, bool_1, int_0]
    var_0 = module_0.sorting(list_0)
    int_1 = 1257
    list_1 = [int_1, int_1]
    var_1 = module_0.sorting(list_1)
    var_2 = module_0.sorting(var_1)


@pytest.mark.xfail(strict=True)
def test_case_26():
    int_0 = 1
    module_0.sorting(int_0)


def test_case_27():
    int_0 = 291
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)
    var_1 = module_0.sorting(list_0)
    var_2 = module_0.sorting(list_0)
    bool_0 = True
    var_3 = module_0.sorting(var_0)
    list_1 = [int_0, bool_0, int_0]
    var_4 = module_0.sorting(list_1)


@pytest.mark.xfail(strict=True)
def test_case_28():
    bool_0 = True
    bool_1 = False
    list_0 = [bool_1]
    var_0 = module_0.sorting(list_0)
    list_1 = [bool_0, bool_0, bool_0, bool_0]
    var_1 = module_0.sorting(list_1)
    var_2 = module_0.sorting(var_0)
    var_3 = module_0.sorting(list_1)
    var_4 = module_0.sorting(list_1)
    var_5 = module_0.sorting(var_4)
    int_0 = -3975
    list_2 = [int_0, int_0]
    var_6 = module_0.sorting(list_2)
    var_7 = module_0.sorting(var_1)
    var_8 = module_0.sorting(list_2)
    var_9 = module_0.sorting(list_1)
    var_10 = module_0.sorting(var_8)
    complex_0 = -1529 + 1385j
    module_0.sorting(complex_0)


@pytest.mark.xfail(strict=True)
def test_case_29():
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_30():
    int_0 = -528
    list_0 = [int_0, int_0]
    int_1 = -3070
    int_2 = 1596
    list_1 = [int_1, int_2]
    var_0 = module_0.sorting(list_1)
    var_1 = module_0.sorting(list_0)
    var_2 = module_0.sorting(list_0)
    var_3 = module_0.sorting(list_0)
    var_4 = module_0.sorting(list_0)
    bytes_0 = b"\x9c\xe0\xfb'"
    module_0.sorting(bytes_0)


def test_case_31():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.sorting(list_0)
    int_0 = -818
    list_1 = [int_0, bool_0]
    var_1 = module_0.sorting(list_1)


@pytest.mark.xfail(strict=True)
def test_case_32():
    int_0 = -1602
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_33():
    bool_0 = False
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_34():
    bytes_0 = b"Ok\xf7\x0c"
    list_0 = []
    var_0 = module_0.sorting(list_0)
    str_0 = '\t-"=y\tgi?&> \x0cG'
    tuple_0 = (bytes_0, bytes_0, str_0)
    bool_0 = True
    int_0 = -2123
    int_1 = -1987
    list_1 = [bool_0, int_0, bool_0, int_1]
    var_1 = module_0.sorting(list_1)
    list_2 = [tuple_0, str_0, bytes_0]
    module_1.object(*list_2)


@pytest.mark.xfail(strict=True)
def test_case_35():
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_36():
    int_0 = 2265
    list_0 = [int_0]
    var_0 = module_0.sorting(list_0)
    bool_0 = True
    bool_1 = True
    list_1 = [int_0, int_0, bool_0, bool_1]
    var_1 = module_0.sorting(list_1)
    var_2 = module_0.sorting(var_1)
    int_1 = 3467
    list_2 = [int_1]
    var_3 = module_0.sorting(list_2)
    module_0.sorting(bool_0)


def test_case_37():
    int_0 = 2755
    int_1 = -1252
    list_0 = [int_0, int_1]
    var_0 = module_0.sorting(list_0)


@pytest.mark.xfail(strict=True)
def test_case_38():
    int_0 = 559
    bool_0 = True
    bool_1 = False
    list_0 = [bool_0, int_0, bool_1]
    var_0 = module_0.sorting(list_0)
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_39():
    int_0 = 1691
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_40():
    bool_0 = False
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_41():
    int_0 = 0
    module_0.sorting(int_0)


@pytest.mark.xfail(strict=True)
def test_case_42():
    bool_0 = True
    int_0 = 39
    list_0 = [bool_0, bool_0, int_0]
    var_0 = module_0.sorting(list_0)
    int_1 = -555
    module_0.sorting(int_1)


@pytest.mark.xfail(strict=True)
def test_case_43():
    bool_0 = True
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_44():
    bool_0 = False
    module_0.sorting(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_45():
    none_type_0 = None
    module_0.sorting(none_type_0)


def test_case_46():
    bool_0 = True
    int_0 = 1
    list_0 = [bool_0, int_0]
    var_0 = module_0.sorting(list_0)
    list_1 = []
    var_1 = module_0.sorting(list_1)


@pytest.mark.xfail(strict=True)
def test_case_47():
    float_0 = 2174.80966
    module_0.sorting(float_0)


@pytest.mark.xfail(strict=True)
def test_case_48():
    none_type_0 = None
    module_0.sorting(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_49():
    dict_0 = {}
    var_0 = module_0.sorting(dict_0)
    bool_0 = False
    module_0.sorting(bool_0)
