# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_2 as module_0


def test_case_0():
    bool_0 = True
    set_0 = {bool_0}
    var_0 = module_0.method(set_0, set_0)
    assert var_0 == 4


def test_case_1():
    none_type_0 = None
    var_0 = module_0.method(none_type_0, none_type_0)
    assert var_0 == 6


def test_case_2():
    list_0 = []
    list_1 = [list_0, list_0, list_0, list_0]
    var_0 = module_0.method(list_1, list_0)
    assert var_0 == 5
