# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import Quicksort as module_0


def test_case_0():
    bytes_0 = b"\xc2"
    var_0 = module_0.quicksort(bytes_0)
    assert var_0 == b"\xc2"


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ")nis;SHP$*4<"
    bytes_0 = b"\x19ri\x82\x14U\x89Pn\x06O\xcc_"
    tuple_0 = (str_0, bytes_0, str_0)
    module_0.quicksort(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\xe5\xae\xb8\xb7"
    module_0.quicksort(bytes_0)
