# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_2 as module_0


def test_case_0():
    int_0 = 4626
    var_0 = module_0.method(int_0, int_0)
    assert var_0 == 4


def test_case_1():
    float_0 = 409.6697
    bool_0 = False
    var_0 = module_0.method(float_0, bool_0)
    assert var_0 == 5


def test_case_2():
    none_type_0 = None
    int_0 = 384
    var_0 = module_0.method(none_type_0, int_0)
    assert var_0 == 5
