# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import test_example_3 as module_0


def test_case_0():
    int_0 = 124
    int_1 = 625
    int_2 = -207
    list_0 = [int_0, int_1, int_2]
    var_0 = module_0.sorting(list_0)
